spring:
  application:
     name: redencion-api
  datasource:
    url: jdbc:oracle:thin:@dbmed06:1522:dllo11g3
    username: PORTAL_PAGOS
    password: pagos
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 1001
  servlet:
    context-path: /redencion