spring:
  application:
     name: puntos-api
  datasource:
    url: jdbc:oracle:thin:@10.125.63.229:1521:ORCUTF8
    username: ORAATHFIDELIZACIONDEV
    password: ORAATHFIDELIZACIONDEV
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 1001
  servlet:
    context-path: /puntos